yatube/about/urls.py
from django.urls import path

from about import views

app_name = '%(app_label)s'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = '%(app_label)s'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='index_name'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:pk>/edit/', views.post_edit, name='update_post'),
    path('posts/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from yatube.settings import UPLOAD_TO

User = get_user_model()
TEXT_SIZE = 15
MY_FOLLOW = '{} подписан на {}'


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    slug = models.SlugField(
        max_length=30,
        unique=True,
        verbose_name='читаемая часть URL',
    )
    description = models.TextField(verbose_name='описание')

    class Meta:
        verbose_name = 'группа статей '
        verbose_name_plural = 'группы статей'
        ordering = ('-title',)

    def __str__(self) -> str:
        return self.title[:TEXT_SIZE]


class Post(models.Model):
    text = models.TextField(verbose_name='текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата публикации',
        db_index=True,
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='группа',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='автор',
    )
    image = models.ImageField(
        verbose_name='картинка',
        upload_to=UPLOAD_TO,
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        default_related_name = 'posts'
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

    def __str__(self) -> str:
        return self.text[:TEXT_SIZE]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='автор',
    )
    text = models.TextField(verbose_name='текст')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата публикации',
        db_index=True,
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self) -> str:
        return self.text[:TEXT_SIZE]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='блогер',
    )

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'
        constraints = [
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_author_check',
            ),
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_following'
            ),
        ]

    def __str__(self):
        return MY_FOLLOW.format(self.user.username, self.author.username)

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from core.utils import paginate
from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User


def group_posts(request, slug: str) -> None:
    group = get_object_or_404(Group, slug=slug)
    return render(
        request,
        'posts/group_list.html',
        {
            'group': group,
            'page_obj': paginate(request, group.posts.all()),
        },
    )


def index(request) -> None:
    return render(
        request,
        'posts/index.html',
        {
            'page_obj': paginate(
                request, Post.objects.select_related('group', 'author')
            ),
        },
    )


def profile(request, username: str) -> None:
    author = get_object_or_404(User, username=username)
    return render(
        request,
        'posts/profile.html',
        {
            'author': author,
            'page_obj': paginate(
                request, author.posts.select_related('group', 'author')
            ),
            'following': Follow.objects.select_related('user', 'author'),
        },
    )


def post_detail(request, pk: int):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'), pk=pk
    )
    comments = post.comments.all().select_related('author')
    form = CommentForm(request.POST or None)
    return render(
        request,
        'posts/post_detail.html',
        {
            'post': post,
            'form': form,
            'comments': comments,
        },
    )


@login_required
def create_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})

    form.instance.author = request.user
    form.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, pk: int):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        return redirect('posts:post_detail', pk)
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(
            request,
            'posts/create_post.html',
            {
                'form': form,
                'pk': pk,
                'is_edit': True,
            },
        )

    form.save()
    return redirect('posts:post_detail', pk)


@login_required
def add_comment(request, pk):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=pk)
        comment.save()
    return redirect('posts:post_detail', pk=pk)


@login_required
def follow_index(request):
    post_list = Post.objects.select_related("author", "group").filter(
        author__following__user=request.user
    )
    page_obj = paginate(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow, user=request.user, author__username=username
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
 
  {% if is_edit %}
    Редактировать статью
  {% else %}
    Добавить статью
  {% endif %}
 
{% endblock %}
{% block content %}
  {% if not is_edit %}
    Добавить статью
  {% else %}
    Редактировать статью
  {% endif %}
 
  <div class="card-body">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
 
            <div class="alert alert-danger">{{ error|escape }}</div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">{{ error|escape }}</div>
        {% endfor %}
      {% endif %}
      <form method="post"
            action="{% if not is_edit %} {% url 'posts:create_post' %} {% else %} {% url 'posts:update_post' pk %} {% endif %}">
        {% csrf_token %}
        {% for field in form %}
 
          <div class="form-group">
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
            </div>
          </div>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
      {% endfor %}
      <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary">
          {% if is_edit %}
            Сохранить
          {% else %}
            Добавить
          {% endif %}
 
        </button>
      </div>
    </form>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}Последние обновления на сайте{% endblock %}
 

{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
    {% include 'posts/includes/post.html' %}
 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock title %}
{% block content %}
  <p>
    <h1>{{ group.title }}</h1>
  </p>
  <p>{{ group.description|linebreaks }}</p>
  {% for post in posts %}
    {% include "posts/includes/post.html"  with hide_group_link=True %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/switcher.html' with index=True %}
    {% cache 20 index_page page_obj %}
    {% for post in page_obj %}
      {% include "posts/includes/post.html" %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %}
</div>
{% include "includes/paginator.html" %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
 
  Подробности статьи {{ post.text|truncatechars:30 }}
{% endblock title %}
 
{% block content %}
  <div class="container py-5">
    <div class="row">
      <h1>Подробная информация о посте</h1>
      <ul>
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.group %}
        <li class="list-group-item">
          <a href="{% url 'posts:group_posts' post.group.slug %}">Все статьи {{ post.group }}</a>
        </li>
      {% endif %}
      <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего статьей автора: {{  post.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">все статьи пользователя</a>
      </li>
      <article class="col-12 col-md-9">
        <p>{{ post.text|linebreaks }}</p>
        {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:update_post' post.pk %}">
            редактировать статью
          </a>
        {% endif %}
        {% include 'posts/includes/comments.html' %}
      </article>
    </ul>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <h1>Все статьи пользователя {{ author.get_full_name }}</h1>
    <h2>Всего статьей: {{ author.posts.count }}</h2>
    <h1>Подписки: {{ author.following.count }}</h1>
    <h1>Подписчики: {{ author.followers.count }}</h1>
    <h1>Комментарии: {{ author.comments.count }}</h1>
    <div class="mb-5">
      {% if user.is_authenticated and user != author %}
        {% if following %}
          <a class="btn btn-lg btn-light"
             href="{% url 'posts:profile_unfollow' author.username %}"
             role="button">
            Отписаться
          </a>
        {% else %}
          <a class="btn btn-lg btn-primary"
             href="{% url 'posts:profile_follow' author.username %}"
             role="button">
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      {% include "posts/includes/post.html" with hide_profile_link=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock content %}